In [1]:
from simfin import simulator, replicator

In [2]:
x = simulator(2021,2035)

In [3]:
x.simulate()

In [4]:
x.macro.aggr

,Y,Yp,H,E,N,infl,YperH,sp500,b1yr,b5yr,...,b30yr,gr_wage,gr_Y,gr_H,gr_Yp,gr_YperH,gr_wage_p,gr_YperH_p,gr_N,gr_E
2021,473285.161374,471686.240659,1475773.335223,4104104.675086,8478492.841146,0.030951,0.320703,0.058128,0.001375,0.009584,...,0.031372,0.075655,0.070781,-0.004874,0.067163,0.044704,0.065951,0.035000,-0.011205,0.001099
2022,503679.088221,501087.83955,1482530.441988,4106224.116298,8528265.486811,0.025907,0.339743,-0.08102,0.00423,0.013418,...,0.034336,0.05964,0.064219,0.004579,0.062333,0.033734,0.055282,0.029375,0.005870,0.000516
2023,535804.299223,540402.558173,1470930.648977,4109757.378132,8571435.357161,0.05107,0.364262,0.25849,0.002002,0.01558,...,0.035987,0.071605,0.063781,-0.007824,0.078459,0.020535,0.074820,0.023750,0.005062,0.000860
2024,556363.044462,566829.176726,1479344.362819,4114226.581829,8620849.573095,0.018155,0.376088,0.278899,0.011974,0.020428,...,0.039556,0.03265,0.03837,0.00572,0.048902,0.014495,0.036280,0.018125,0.005765,0.001087
2025,553632.038561,590166.117714,1475567.671654,4122205.154011,8668974.091905,0.019717,0.375199,-0.042058,-0.005557,0.009166,...,0.033597,-0.002356,-0.004909,-0.002553,0.041171,-0.022073,0.032217,0.012500,0.005582,0.001939
2026,585734.199203,617748.205559,1511643.746176,4134771.267868,8716103.107638,0.019881,0.387482,0.140435,0.001147,0.009618,...,0.032445,0.033536,0.057985,0.024449,0.046736,0.013655,0.032381,0.012500,0.005437,0.003048
2027,604924.206713,631558.38484,1515525.36225,4147078.905645,8765251.221693,0.016805,0.399151,0.154577,-0.004327,0.005694,...,0.0274,0.030195,0.032762,0.002568,0.022356,0.01339,0.029305,0.012500,0.005639,0.002977
2028,624301.635363,642333.967894,1464227.571539,4161408.668771,8812406.067776,0.010598,0.426369,0.039511,0.002981,0.012335,...,0.032753,0.065881,0.032033,-0.033848,0.017062,0.055283,0.023098,0.012500,0.005380,0.003455
2029,649167.330803,682316.030451,1509053.167918,4176851.06609,8858905.387996,0.017226,0.430182,0.032896,0.004596,0.016222,...,0.039007,0.009216,0.03983,0.030614,0.062245,-0.00801,0.029726,0.012500,0.005277,0.003711
2030,658570.289565,718859.786857,1551212.305564,4192860.890928,8906231.153818,0.034806,0.424552,0.004361,-0.00192,0.008483,...,0.031132,-0.013453,0.014485,0.027937,0.053558,-0.048259,0.047306,0.012500,0.005342,0.003833
2031,658885.94028,723836.324372,1529863.611368,4210749.285849,8948772.094421,0.010929,0.430683,-0.02024,0.001693,0.00986,...,0.03063,0.014242,0.000479,-0.013763,0.006923,0.003313,0.023429,0.012500,0.004777,0.004266
2032,668434.562964,739160.973964,1591201.451805,4230235.290934,8991299.84176,0.006513,0.420082,-0.049693,0.001549,0.017672,...,0.040306,-0.025602,0.014492,0.040094,0.021171,-0.032114,0.019013,0.012500,0.004752,0.004628
2033,672502.241127,743063.632986,1476027.460582,4249204.751105,9033967.980083,0.024401,0.455616,-0.090737,0.01598,0.029887,...,0.050303,0.078467,0.006085,-0.072382,0.00528,0.054066,0.036901,0.012500,0.004745,0.004484
2034,722358.30911,798875.129701,1521406.158685,4266585.666707,9074262.16624,0.013636,0.474796,0.020623,-0.001315,0.018507,...,0.04479,0.043391,0.074135,0.030744,0.07511,0.029756,0.026136,0.012500,0.004460,0.004090

In [5]:
x.revenue.report

,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034
personal_taxes,31150.637342,33426.913286,36401.976403,38499.282721,40431.140261,42638.459525,44138.943390,45403.890673,48313.414628,51326.815410,52407.445012,54001.045884,55255.601335,59148.360203
personal_credits_other,1548.454152,1644.973881,1774.036452,1860.789899,1937.400536,2027.947163,2073.283295,2108.657438,2239.910770,2359.876812,2376.213816,2426.521659,2439.333329,2622.551614
personal_credits_family,3770.531575,3971.471080,4265.895689,4391.245144,4510.469503,4670.812955,4632.929057,4618.445699,4636.576974,4715.966401,4613.940881,4517.950515,4438.346132,4292.645955
corporate_taxes,7048.614524,7487.975521,8075.472617,8470.377177,8819.111329,9231.282574,9437.654144,9598.678412,10196.147921,10742.237313,10816.603897,11045.606862,11103.926009,11937.941701
corporate_credits,2136.461208,2269.633156,2447.705705,2567.402742,2673.105357,2798.035990,2860.587978,2909.395031,3090.490256,3256.011976,3278.552763,3347.964411,3365.641161,3618.434411
fss,6960.039958,7393.879841,7973.994309,8363.936404,8708.288280,9115.280083,9319.058339,9478.059137,10068.020703,10607.247805,10680.679881,10906.805141,10964.391435,11787.926688
property_taxes,1642.364535,1744.737975,1881.627912,1973.642767,2054.899672,2150.937756,2199.023426,2236.542933,2375.756495,2502.998217,2520.326025,2573.684930,2587.273600,2781.603676
consumption,22981.980009,24486.038381,26552.885713,27776.949732,28926.362541,30176.815806,31348.606727,32358.911091,33619.840072,35510.551263,36635.400954,37620.072311,39288.668778,40587.567965
permits,4839.586202,5141.251928,5544.628057,5815.769947,6055.211185,6338.208399,6479.903338,6590.462770,7000.685969,7375.631524,7426.691699,7583.925378,7623.967366,8196.603424
gov_enterprises,4715.795243,5009.744713,5402.802952,5667.009348,5900.325960,6176.084435,6314.154983,6421.886435,6821.616603,7186.971489,7236.725605,7389.937430,7428.955190,7986.943887
miscellaneous_income,9412.381544,9999.083133,10783.598559,11310.935155,11776.618005,12327.011704,12602.590394,12817.614472,13615.446581,14344.668145,14443.973713,14749.773281,14827.649871,15941.354398

In [6]:
x.missions.report

,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034
health,45819.889775,47871.279795,50985.002256,52921.787162,55012.555654,57165.966351,59385.060709,61271.715450,63652.246597,67260.589261,69304.194951,71118.525018,74352.145906,76877.602946
education,27837.452611,30262.341590,33675.123683,35568.367213,36063.664793,38784.613910,40615.524166,42413.462489,44781.025948,46756.449366,47210.953889,48117.067218,49510.332186,53604.821985
economy,18454.457375,19604.778302,21142.944431,22176.870935,23089.915551,24169.049137,24709.364591,25130.953183,26695.228766,28124.982566,28319.686781,28919.255029,29071.944356,31255.537597
family_credit,3770.531575,3971.471080,4265.895689,4391.245144,4510.469503,4670.812955,4632.929057,4618.445699,4636.576974,4715.966401,4613.940881,4517.950515,4438.346132,4292.645955
family_kg,2917.507073,3080.122864,3318.062175,3446.879752,3561.761839,3676.410064,3778.723181,3857.913478,3960.583648,4134.134548,4218.952100,4287.478361,4434.771144,4545.602293
family_other,4980.451776,5290.898071,5706.015247,5985.049248,6231.459890,6522.694288,6668.513534,6782.291014,7204.454557,7590.313632,7642.860013,7804.670284,7845.877772,8435.181517
justice,10141.254174,10773.388550,11618.655001,12186.827300,12688.571531,13281.586420,13578.505274,13810.180310,14669.794655,15455.485417,15562.480974,15891.960940,15975.868109,17175.815289

In [8]:
x.federal.report

,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034
equalization,8873.392698,9139.594479,9606.354834,9894.545479,10191.381843,10497.123298,10812.036997,11136.398107,11470.490051,11869.735463,12225.827526,12592.602352,12970.380423,13359.491835
health_transfer,6809.429392,7013.712273,7371.903529,7593.060635,7820.852454,8055.478028,8297.142369,8546.056640,8802.438339,9108.818721,9382.083282,9663.545781,9953.452154,10252.055719
other_transfers,2063.963307,2125.882206,2234.451304,2301.484844,2370.529389,2441.645271,2514.894629,2590.341468,2668.051712,2760.916742,2843.744244,2929.056571,3016.928268,3107.436116

In [ ]:
numbers = [4, 5, 7, 1, 3, 6, 9, 8, 0]
output = numbers.sort()
print("The Value in the output variable is:", output)
print(output[0])

In [ ]:
numbers.type

In [ ]:
x.pop.head()

In [ ]:
mc = replicator(nreps=100,ncpus=8)

In [ ]:
mc.set_model(x)

In [ ]:
mc.replicate()

In [ ]:
mc.stats